spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
service:
  mail:
    email: vitalik@gmail.com
    user-name: default
    password: qwe321
clients:
  description:
    url: http://localhost:8877/api/v1/file/